### ISSUE TITLE
AttributeError: 'SQLite' object has no attribute 'file_open'

### ISSUE THREAD

**Issue by sarbjit87** [web2py/pydal#488]
On using web2py latest version, following error is reported while connecting to database using DAL. It works with web2py 2.14.6

AttributeError: 'SQLite' object has no attribute 'file_open'

Sample Code :-

# Assumption : script is placed inside scripts folder in application
scriptPath = os.path.dirname(os.path.realpath(__file__))
dbPath = os.path.abspath(os.path.join(scriptPath,"../databases"))
libraryPath = os.path.abspath(os.path.join(scriptPath,"../../.."))
sys.path.append(libraryPath)
from gluon import DAL
print dbPath, libraryPath
db = DAL('sqlite://storage.sqlite',folder=dbPath,auto_import=True)

I get the following error :-

Traceback (most recent call last):

  File "populate_database.py", line 19, in <module>

    db = DAL('sqlite://storage.sqlite',folder=dbPath,auto_import=True)
  File "/Users/sarbjit/Data/development/python/web2py/gluon/packages/dal/pydal/base.py", line 170, in __call__
    obj = super(MetaDAL, cls).__call__(*args, **kwargs)
  File "/Users/sarbjit/Data/development/python/web2py/gluon/packages/dal/pydal/base.py", line 500, in __init__
    tables=tables)

  File "/Users/sarbjit/Data/development/python/web2py/gluon/packages/dal/pydal/base.py", line 522, in import_table_definitions

    tfile = self._adapter.file_open(filename, 'r')

AttributeError: 'SQLite' object has no attribute 'file_open'

**Comment by gonguinguen** [comment]
Same problem here, but using PostgreSQL. The error is the same, but it says 
`'PostgrePsyco' object has no attribute 'file_open'`

This is the function I use to connect to the database:
`def connect_db(db_host, db_name, db_user, db_user_password):
    # gets the table_hash from one of the .table files in the databases folder
    table_hash = None
    for file in os.listdir(databases_folder):
        if archivo.endswith('.table'):
            table_hash = file.split('_')[0]
            break
    return DAL('postgres://%s:%s@%s:5432/%s' % (db_user, db_user_password, db_host, db_name),
               migrate=False,
               folder=databases_folder,
               auto_import=True,
               table_hash=table_hash)`


Here is the complete traceback:

`Traceback (most recent call last): File "/home/gonguinguen/medios/gluon/scheduler.py", line 501, in executor result = dumps(_function(*args, **vars)) File "applications/webmedios/models/scheduler.py", line 13, in update_stats_publicidades return funcion() File "applications/webmedios/modules/funciones_scheduler.py", line 27, in update_stats_publicidades dbs = sitio.conectar_db() File "/home/gonguinguen/medios/gluon/packages/dal/pydal/objects.py", line 2368, in __call__ return self.method(self.row, *args, **kwargs) File "applications/webmedios/models/db.py", line 149, in <lambda> Field.Method('conectar_db', lambda row: sitios_conectar_db(row.sitios)), File "applications/webmedios/modules/virtual_methods.py", line 79, in sitios_conectar_db table_hash=table_hash) File "/home/gonguinguen/medios/gluon/packages/dal/pydal/base.py", line 170, in __call__ obj = super(MetaDAL, cls).__call__(*args, **kwargs) File "/home/gonguinguen/medios/gluon/packages/dal/pydal/base.py", line 500, in __init__ tables=tables) File "/home/gonguinguen/medios/gluon/packages/dal/pydal/base.py", line 522, in import_table_definitions tfile = self._adapter.file_open(filename, 'r') AttributeError: 'PostgrePsyco' object has no attribute 'file_open'`


Let me know if I can help in anyway to fix this.
Regards,
Lisandro.

**Comment by leonelcamara** [comment]
Can you guys test with the trunk version? It looks like Massimo fixed it here
https://github.com/web2py/pydal/commit/c995fd7c9b2d445ad020960444e67a987f97761a

**Comment by gonguinguen** [comment]
It worked perfectly for me! 
I confirm that this fixed the problem for me.

**Comment by sarbjit87** [comment]
It worked for me as well :)

**Comment by leonelcamara** [comment]
@mdipierro looks like this issue can be closed :)

**Comment by mdipierro** [comment]
Thanks everybody!
